package threshsig;

import java.math.BigInteger;

/**
 * A GroupKey with information common to all the keyshares. Generated by the
 * Dealer class
 *
 * Reference: "Practical Threshold Signatures",<br>
 * Victor Shoup (sho@zurich.ibm.com), IBM Research Paper RZ3121, 4/30/99<BR>
 *
 * @author Steve Weis <sweis@mit.edu>
 */
public class GroupKey {
  /** (k,l) Parameters. k out of l shares needed for a signature */
  private int k, l;

  /** The exponent of the groupKeyPair */
  private BigInteger e;

  /** The RSA modulus of the groupKeyPair */
  private BigInteger n;

  public GroupKey(final int k, final int l, final int keysize, final BigInteger v,
      final BigInteger e, final BigInteger n) {
    this.k = k;
    this.l = l;
    this.e = e;
    this.n = n;
  }

  public int getK() {
    return k;
  }

  public int getL() {
    return l;
  }

  public BigInteger getModulus() {
    return n;
  }

  public BigInteger getExponent() {
    return e;
  }
}
